# Generated by Django 5.2.6 on 2025-09-10 00:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submittal_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('spec_section', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('IN_REVIEW', 'In Review'), ('READY_PIC_REVIEW', 'Ready for PIC Review'), ('READY_TO_RETURN', 'Ready to Return'), ('RETURNED', 'Returned'), ('VOID', 'Void')], default='IN_REVIEW', max_length=20)),
                ('originator', models.CharField(max_length=120)),
                ('date_received', models.DateField()),
                ('date_logged', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_pm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_submittals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submittals', to='projects.project')),
            ],
            options={
                'ordering': ['due_date', 'date_received'],
                'indexes': [models.Index(fields=['project', 'status'], name='submittals__project_c63844_idx'), models.Index(fields=['due_date'], name='submittals__due_dat_bc1b56_idx'), models.Index(fields=['assigned_pm'], name='submittals__assigne_22ccb0_idx')],
            },
        ),
    ]
