# Generated by Django 5.2.6 on 2025-09-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
