# Generated by Django 5.2.6 on 2025-09-10 00:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_business_day', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
