# Generated by Django 5.2.6 on 2025-09-10 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rfi_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('originator', models.CharField(max_length=120)),
                ('date_received', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('date_responded', models.DateField(blank=True, null=True)),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('AWAITING_RESPONSE', 'Awaiting Response'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_rfis', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfis', to='projects.project')),
            ],
            options={
                'ordering': ['due_date', 'date_received'],
                'indexes': [models.Index(fields=['project', 'status'], name='rfis_rfi_project_168ab2_idx'), models.Index(fields=['due_date'], name='rfis_rfi_due_dat_d06144_idx'), models.Index(fields=['assigned_to'], name='rfis_rfi_assigne_b056e3_idx')],
            },
        ),
    ]
