# Generated by Django 5.2.6 on 2025-09-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfi',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rfi',
            name='response',
        ),
        migrations.AddField(
            model_name='rfi',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='rfi',
            name='status',
            field=models.CharField(choices=[('IN_REVIEW', 'In Review'), ('READY_PIC_REVIEW', 'Ready for PIC Review'), ('READY_TO_RETURN', 'Ready to Return'), ('RETURNED', 'Returned'), ('VOID', 'Void')], default='IN_REVIEW', max_length=20),
        ),
    ]
