# Generated by Django 5.2.6 on 2025-09-10 03:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('rfis', '0002_remove_rfi_question_remove_rfi_response_rfi_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi',
            name='rfi_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='rfi',
            index=models.Index(fields=['rfi_number'], name='rfis_rfi_rfi_num_91599e_idx'),
        ),
    ]
