# Generated by Django 5.2.6 on 2025-09-10 00:07

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('principals', models.ManyToManyField(blank=True, related_name='principal_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
                'indexes': [models.Index(fields=['active'], name='projects_pr_active_631fc0_idx')],
            },
        ),
    ]
